### PR TITLE
in touch-control, two fingers reverses the camera

### PR DESCRIPTION
**Pull request by morandd**
Extended so that with two fingers down, the camera flies in reverse (increasing along the Z axis).

### CODE REVIEW

**Comment by donmccurdy** [comment]
Hi @morandd! This is a cool locomotion option, and I could see it being helpful in certain situations. But I don't think it's general enough that I want to include the feature in aframe-extras, because it can't be used with Cardboard or Daydream headsets where the device is inside a viewer.

If you just want to have this option in your own demo, you can make a new component:

```js
AFRAME.registerComponent('reversible-touch-controls', {
  // ...
});
```

And then you can register that component with `universal-controls` like this:

```html
<a-entity camera universal-controls="movementControls: gamepad, keyboard, reversible-touch, hmd;"></a-entity>
```

This way you don't have to make a copy of all of aframe-extras just to have customized touch controls. :)

**Comment by morandd** [comment]
Ok, thanks for the suggestion.

But pinch to move forward/zoom seemed like a quite obvious gesture when I
open an afame scene on my mobile phone without entering vr mode.

**Comment by morandd** [comment]
Another comment in case anyone else stumbles upon this thread: 

orbit-controls supports pinch to zoom.

My solution in this case was to set up two cameras, one with orbit-controls on it and the other with look-controls, then switch to use the look-controls camera when the user enters VR mode.  That way they get touch control to orbit/zoom around the 3d object when they just open my aframe page, and get look-controls if they put the phone inside a Cardboard.
 
Here are the relevant code bits.


```
		<a-entity
            camera
            id="camera_orbit"
            position="0 2 6"
			active="true"
			orbit-controls="
                autoRotate: false;
                target: #target;
                enableDamping: true;
                dampingFactor: 0.125;
                rotateSpeed:0.15;
				zoomSpeed:0.5;
				maxPolarAngle:1.85;
                minDistance:1;
                maxDistance:10;">
		</a-entity>
				
		<a-entity
			camera
			id="camera_look"
			active="false"
			position="0 2 6"
			look-controls
			wasd-controls="fly:true" 
			mouse-cursor="">
		</a-entity>
```


Then added this script to my page:
```
  <script>
	/*
	* Switch from the oribt- camera to the look-controls camera when we enter VR mode 
	*/
	document.addEventListener("DOMContentLoaded", function(event) {
		var scene = document.querySelector('a-scene');
		if (scene.hasLoaded) addEventListeners();
		else scene.addEventListener( 'loaded', addEventListeners );
	});
	function addEventListeners() {
		
		document.querySelector('a-scene').addEventListener('enter-vr', function(evt){
			document.querySelector('#camera_orbit').setAttribute('camera', 'active', false);
			document.querySelector('#camera_look').setAttribute('camera', 'active', true);
		});
		
		document.querySelector('a-scene').addEventListener('exit-vr', function(evt){
			document.querySelector('#camera_orbit').setAttribute('camera', 'active', true);
			document.querySelector('#camera_look').setAttribute('camera', 'active', false);
		});
	} // end addEventListeners()
	
  </script>
```

**Comment by morandd** [comment]
FYI, I created a multitouch-look-controls camera controller to address my
needs. It provides pinch to zoom, two finger drag to dolly, and single
finger yaw and pitch. It converts itself to a standard look-controls if
it's on desktop or in VR mode.

http://github.com/morandd/aframe-multitouch-look-controls

**Comment by donmccurdy** [comment]
Nice! looks good!

**Pull request closed without merging**
