### PR TITLE
Remove kinematic-body, jump-ability & related  components

### PR DESCRIPTION
**Pull request by diarmidmackenzie**
As per [this comment](https://github.com/c-frame/aframe-extras/issues/395#issuecomment-1375870355)

I've added a brief list of removed components.  I think this could be useful if someone comes to aframe-extras looking for something that existed in the past, nice to give them some indication that it's gone.

I've included a-hexgrid in that list, even though it's being removed under a separate PR #408.  Making the change here avoids merge conflicts.

This assumes we merge this & #408 around the same time.  If we end up not doing that we'll need to do a little bit of fix-up of this list.

### CODE REVIEW

**Comment by diarmidmackenzie** [comment]
Extending this to also remove cube-env-map.

**Comment by vincentfretin** [comment]
Need a rebase and change version to 7.0.0.

**Comment by diarmidmackenzie** [comment]
Should be ready to merge now.

**Comment by vincentfretin** [comment]
Thank you.

**Pull request merged**
