### PR TITLE
Add iterations to schema, add gravity to readme

### PR DESCRIPTION
**Pull request by bryik**
Noticed a few things while experimenting.

**Proposed Changes:**
- Add iterations to schema (it is listed as a system property after all).
- Add gravity to system property list. This is the reverse problem (gravity is in the schema, but is not listed as a system property).
- Fix a typo in the physics readme.

The "dev" and "build" commands weren't working for me, so I couldn't test.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks @bryik! Looks good.

I am curious about `dev` and `build` errors, though – what OS are you on? Those commands don't work on Windows yet.

**Comment by bryik** [comment]
> Those commands don't work on Windows yet.

Ah, that explains it. I'm on Windows 10.

**Comment by donmccurdy** [comment]
Ok, yeah. I'm planning to either fix that or get a recommended workflow with the new "Bash on Ubuntu on Windows" thing.

**Comment by bryik** [comment]
I gave Bash on Windows a go, but ran into the [os.networkInterfaces error](https://github.com/Microsoft/BashOnWindows/issues/468). It looks like a common problem, so hopefully Microsoft will fix it soon.

**Comment by donmccurdy** [comment]
Good to know, thanks!

**Pull request merged**
