### PR TITLE
Swipe movement for trackpad

### PR DESCRIPTION
**Pull request by stlewis**
New PR for adding swipe-based movement to trackpad-controls. The default is still touch, and there are a handful of new options for controlling movement via trackpad.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks!

This looks good, but I think it will need some documentation for how to use it... as far as I can tell:

1. requires that `gearvr-controls` be somewhere in the scene, or the necessary events aren't fired
2. requires that `gamepad-controls` be disabled (on Oculus Go at least)
3. the `swipe` mode feels a bit weird in Oculus Go, but maybe I've got something set up wrong

**Comment by stlewis** [comment]
@donmccurdy Yeah, the swipe controls are screwy unless you explicitly _don't_ enable gamepad controls...it's a bit odd, but I haven't been able to track down a specific culprit yet. What would be the best way to document the changes?

**Comment by donmccurdy** [comment]
If you could just put a note somewhere here that'd be great https://github.com/donmccurdy/aframe-extras/tree/master/src/controls, thanks. :)

**Comment by stlewis** [comment]
There's not a super-obvious place to inject docs specific to that control method. Should I just create another heading to the effect of "Using With Trackpad Controls"?

**Comment by donmccurdy** [comment]
If you just want to write up suggested usage in a paragraph and/or example I can figure out how to organize it. 👍

**Pull request merged**
